
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";

CREATE TABLE IF NOT EXISTS `accounts` (
  `accid` int(11) NOT NULL AUTO_INCREMENT,
  `account_type`  varchar(200) NOT NULL DEFAULT 'SAVINGS ACCOUNT',
  `is_admin` tinyint(1) NOT NULL DEFAULT '0',
  `email` varchar(160) DEFAULT NULL UNIQUE,
  `mobile` varchar(25) DEFAULT NULL,
  `password` varchar(160) DEFAULT NULL,
  `title` varchar(25) NOT NULL,
  `firstname` varchar(160) DEFAULT NULL,
  `lastname` varchar(160) DEFAULT NULL,
  `sex`  varchar(25) NOT NULL,
  `balance` decimal(20,2) NOT NULL DEFAULT '0.00',
  `kyc`  varchar(200) NOT NULL,
  `kyc_approved` tinyint(1) NOT NULL DEFAULT '0',
  `address` varchar(200) DEFAULT NULL,
  `address2` varchar(200) DEFAULT NULL,
  `city` varchar(200) DEFAULT NULL,
  `zipcode` varchar(15) DEFAULT NULL,
  `state` varchar(200) DEFAULT NULL,
  `country` varchar(200) DEFAULT NULL,
  `currency` varchar(3) NOT NULL DEFAULT 'USD',
  `new_account` tinyint(1) NOT NULL DEFAULT '1',
  `reset_password`  tinyint(1) NOT NULL DEFAULT '1',
  `transfer_error` varchar(200) DEFAULT NULL,
  `avatar` varchar(200) NOT NULL DEFAULT './_store/accounts/profiles/avatar.png',
  `profile_photo` varchar(200) NOT NULL DEFAULT './_store/accounts/profiles/avatar.png',
  `identification` varchar(200) DEFAULT NULL,
  `utility` varchar(200) DEFAULT NULL,  
  `taxcode` varchar(200) DEFAULT NULL,
  `taxcode_verified` tinyint(1) NOT NULL DEFAULT '0',
  `taxcode_verified_date` datetime DEFAULT NULL,
  `error_code` varchar(200) DEFAULT NULL,
  `denytransfer` tinyint(1) NOT NULL DEFAULT '0',
  `enable_error` tinyint(1) NOT NULL DEFAULT '1',
  `enable_warning` tinyint(1) NOT NULL DEFAULT '0',
  `email_notix` tinyint(1) NOT NULL DEFAULT '0',
  `sms_notix` tinyint(1) NOT NULL DEFAULT '0',
  `profile_notix` tinyint(1) NOT NULL DEFAULT '1',
  `otp_enabled` tinyint(1) NOT NULL DEFAULT '0',
  `lastlogin` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `enabled` tinyint(1) NOT NULL DEFAULT '0',
  `created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`accid`)
);


CREATE TABLE IF NOT EXISTS `activities` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `accid` int DEFAULT NULL,
  `osystem` varchar(100) DEFAULT 'UNKNOWN',
  `browser` varchar(100) NOT NULL DEFAULT 'UNKNOWN',
  `device` varchar(100) NOT NULL DEFAULT 'UNKNOWN',
  `ipaddr` varchar(17) DEFAULT NULL,
  `details` text NOT NULL,
  `report` varchar(200) DEFAULT NULL,
  `risklevel` enum('low','medium','high') NOT NULL DEFAULT 'low',
  `created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
);
  
CREATE TABLE IF NOT EXISTS `cms` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `pageid` int DEFAULT NULL,
  `webpart` int DEFAULT NULL,
  `cmskey` varchar(100) DEFAULT NULL UNIQUE,
  `cms` text,
  `stamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `admin` varchar(100) DEFAULT NULL,
  `disabled` tinyint(1) DEFAULT '0',
    PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `pages` (
  `pageid` int(11) NOT NULL AUTO_INCREMENT,
  `sort` int(11) DEFAULT NULL,
  `pagestyle` enum('page','blog') NOT NULL DEFAULT 'page',
  `shortname` varchar(200) DEFAULT NULL,
  `menutitle` varchar(100) DEFAULT NULL,
  `title` varchar(200) DEFAULT NULL,
  `parent` varchar(30) NOT NULL DEFAULT 'home',
  `showtop` varchar(4) NOT NULL DEFAULT 'NO',
  `showheader` tinyint(1) NOT NULL DEFAULT '1',
  `showfooter` tinyint(1) DEFAULT '1',
  `categories` varchar(225) DEFAULT '["cat2"]',
  `enabled` varchar(4) NOT NULL DEFAULT 'YES',
  `metakey` varchar(300) DEFAULT NULL,
  `metades` varchar(300) DEFAULT NULL,
  `excerpt` text,
  `content` mediumtext,
  `photo` text,
  `created` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`pageid`)
);

INSERT INTO `pages` (`pageid`, `sort`, `pagestyle`, `shortname`, `menutitle`, `title`, `parent`) VALUES
(1000, '0', 'page', 'home', 'Home', 'Welcome to Default Website','0');


CREATE TABLE IF NOT EXISTS `settings` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `caption` varchar(360) DEFAULT NULL,
  `name` varchar(100) NOT NULL UNIQUE,
  `value` varchar(260) DEFAULT NULL,
  `type` enum('input','textarea','radio','checkbox','file') NOT NULL DEFAULT 'input',
  `disabled` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
);


INSERT INTO `settings` (`id`, `caption`, `name`, `value`, `type`, `disabled`) VALUES
(1, 'Application Context Name', 'appname', 'nohenugudd', 'input', 0),
(2, 'Site Domain URL', 'domain', 'http://anthill.com', 'input', 0),
(3, 'Website Title', 'title', 'Anthill Pro.', 'input', 0),
(4, 'Default Landing Page', 'defaultlandingpage', '1000', 'input', 0),
(5, 'Google Page', 'link_google', '#', 'input', 0),
(6, 'LinkedIn Page', 'link_linkedin', '#', 'input', 0),
(7, 'Twitter Page', 'link_twitter', '#', 'input', 0),
(8, 'Facebook Page', 'link_facebook', '#', 'input', 0),
(9, 'YouTube Channel', 'link_youtube', '#', 'input', 0),
(10, 'Instagram Page', 'link_instagram', '#', 'input', 0),
(11, 'Copy Right Text', 'copyright_text', '© 2019 <span>Anthill Pro</span>. All Rights Reserved', 'input', 0);


CREATE TABLE IF NOT EXISTS `webparts` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `page` int(11) DEFAULT NULL,
  `webpart` varchar(300) DEFAULT NULL,
  `params` varchar(1000) NOT NULL DEFAULT '[]',
  `sort` int(11) NOT NULL DEFAULT '0',
  `enabled` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`)
);


CREATE TABLE IF NOT EXISTS `transactions` (
  `tid` int(11) NOT NULL AUTO_INCREMENT,
  `transid` varchar(64) DEFAULT NULL,
  `notes` text NOT NULL,
  `accid` int(11) NOT NULL,
  `transferid` int(11) DEFAULT NULL,
  `amount` decimal(20,2) NOT NULL DEFAULT '0.00',
  `type` enum('DEBIT','CREDIT','FEES','REVERSE') NOT NULL DEFAULT 'FEES',
  `sent` tinyint(1) NOT NULL DEFAULT '0',
  `by_admin` int(11) DEFAULT NULL,
  `created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`tid`)
);


CREATE TABLE IF NOT EXISTS `transfers` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `accid` int(11) DEFAULT NULL,
  `name` text,
  `bankname` text,
  `bankaddress` text,
  `swiftcode` text,
  `iban` text,
  `abaroutine` text,
  `accno` text,
  `accname` text,
  `amount` decimal(11,2) NOT NULL DEFAULT '0.00',
  `status` tinyint(1) NOT NULL DEFAULT '0',
  `created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
);


CREATE TABLE IF NOT EXISTS `currencies` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `code` varchar(4) NOT NULL DEFAULT 'USD',
  `sign` varchar(12) NOT NULL DEFAULT '&#36;',
  `name` varchar(300) NOT NULL DEFAULT 'Dollars',
  `curr_rate` decimal(8,2) NOT NULL DEFAULT '0.00',
  `enabled` tinyint(1) NOT NULL DEFAULT '1',
  `calltime` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
);


INSERT INTO `currencies` (`id`, `code`, `sign`, `name`, `curr_rate`, `enabled`, `calltime`) VALUES
(1, 'USD', '&#36;', 'US Dollars', '1.10', 1, 1683655357),
(2, 'CAD', '&#36;', 'Canadian Dollars', '1.47', 1, 1683655357),
(3, 'JPY', '&#165;', 'Japanese Yen', '148.18', 1, 1683655358),
(4, 'AUD', '&#36;', 'Australian Dollars', '1.62', 1, 1683655358),
(5, 'INR', '&#8377;', 'Indian Rupee ', '89.99', 1, 1683655358),
(6, 'ZAR', '', 'South African Rand', '20.41', 1, 1683655358),
(7, 'EUR', '&#8364;', 'Euros', '1.00', 1, 1683655359),
(8, 'GBP', '&#163;', 'Pound Sterling', '0.87', 1, 1683655359);


CREATE TABLE  IF NOT EXISTS `countries` (
  `id` int(11) NOT NULL,
  `sortname` varchar(3) NOT NULL,
  `name` varchar(150) NOT NULL,
  `btc` tinyint(1) NOT NULL DEFAULT '1',
  `local` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
);



INSERT INTO `countries` (`id`, `sortname`, `name`, `btc`, `local`) VALUES
(1, 'AF', 'Afghanistan', 1, 0),
(2, 'AL', 'Albania', 1, 0),
(3, 'DZ', 'Algeria', 1, 0),
(4, 'AS', 'American Samoa', 1, 0),
(5, 'AD', 'Andorra', 1, 0),
(6, 'AO', 'Angola', 1, 0),
(7, 'AI', 'Anguilla', 1, 0),
(8, 'AQ', 'Antarctica', 1, 0),
(9, 'AG', 'Antigua And Barbuda', 1, 0),
(10, 'AR', 'Argentina', 1, 0),
(11, 'AM', 'Armenia', 1, 0),
(12, 'AW', 'Aruba', 1, 0),
(13, 'AU', 'Australia', 1, 0),
(14, 'AT', 'Austria', 1, 0),
(15, 'AZ', 'Azerbaijan', 1, 0),
(16, 'BS', 'Bahamas The', 1, 0),
(17, 'BH', 'Bahrain', 1, 0),
(18, 'BD', 'Bangladesh', 1, 0),
(19, 'BB', 'Barbados', 1, 0),
(20, 'BY', 'Belarus', 1, 0),
(21, 'BE', 'Belgium', 1, 0),
(22, 'BZ', 'Belize', 1, 0),
(23, 'BJ', 'Benin', 1, 0),
(24, 'BM', 'Bermuda', 1, 0),
(25, 'BT', 'Bhutan', 1, 0),
(26, 'BO', 'Bolivia', 1, 0),
(27, 'BA', 'Bosnia and Herzegovina', 1, 0),
(28, 'BW', 'Botswana', 1, 0),
(29, 'BV', 'Bouvet Island', 1, 0),
(30, 'BR', 'Brazil', 1, 0),
(31, 'IO', 'British Indian Ocean Territory', 1, 0),
(32, 'BN', 'Brunei', 1, 0),
(33, 'BG', 'Bulgaria', 1, 0),
(34, 'BF', 'Burkina Faso', 1, 0),
(35, 'BI', 'Burundi', 1, 0),
(36, 'KH', 'Cambodia', 1, 0),
(37, 'CM', 'Cameroon', 1, 0),
(38, 'CA', 'Canada', 1, 0),
(39, 'CV', 'Cape Verde', 1, 0),
(40, 'KY', 'Cayman Islands', 1, 0),
(41, 'CF', 'Central African Republic', 1, 0),
(42, 'TD', 'Chad', 1, 0),
(43, 'CL', 'Chile', 1, 0),
(44, 'CN', 'China', 1, 0),
(45, 'CX', 'Christmas Island', 1, 0),
(46, 'CC', 'Cocos (Keeling) Islands', 1, 0),
(47, 'CO', 'Colombia', 1, 0),
(48, 'KM', 'Comoros', 1, 0),
(49, 'CG', 'Congo', 1, 0),
(50, 'CD', 'Congo The Democratic Republic Of The', 1, 0),
(51, 'CK', 'Cook Islands', 1, 0),
(52, 'CR', 'Costa Rica', 1, 0),
(53, 'CI', 'Cote D\'Ivoire (Ivory Coast)', 1, 0),
(54, 'HR', 'Croatia (Hrvatska)', 1, 0),
(55, 'CU', 'Cuba', 1, 0),
(56, 'CY', 'Cyprus', 1, 0),
(57, 'CZ', 'Czech Republic', 1, 0),
(58, 'DK', 'Denmark', 1, 0),
(59, 'DJ', 'Djibouti', 1, 0),
(60, 'DM', 'Dominica', 1, 0),
(61, 'DO', 'Dominican Republic', 1, 0),
(62, 'TP', 'East Timor', 1, 0),
(63, 'EC', 'Ecuador', 1, 0),
(64, 'EG', 'Egypt', 1, 0),
(65, 'SV', 'El Salvador', 1, 0),
(66, 'GQ', 'Equatorial Guinea', 1, 0),
(67, 'ER', 'Eritrea', 1, 0),
(68, 'EE', 'Estonia', 1, 0),
(69, 'ET', 'Ethiopia', 1, 0),
(70, 'XA', 'External Territories of Australia', 1, 0),
(71, 'FK', 'Falkland Islands', 1, 0),
(72, 'FO', 'Faroe Islands', 1, 0),
(73, 'FJ', 'Fiji Islands', 1, 0),
(74, 'FI', 'Finland', 1, 0),
(75, 'FR', 'France', 1, 0),
(76, 'GF', 'French Guiana', 1, 0),
(77, 'PF', 'French Polynesia', 1, 0),
(78, 'TF', 'French Southern Territories', 1, 0),
(79, 'GA', 'Gabon', 1, 0),
(80, 'GM', 'Gambia The', 1, 0),
(81, 'GE', 'Georgia', 1, 0),
(82, 'DE', 'Germany', 1, 0),
(83, 'GH', 'Ghana', 1, 0),
(84, 'GI', 'Gibraltar', 1, 0),
(85, 'GR', 'Greece', 1, 0),
(86, 'GL', 'Greenland', 1, 0),
(87, 'GD', 'Grenada', 1, 0),
(88, 'GP', 'Guadeloupe', 1, 0),
(89, 'GU', 'Guam', 1, 0),
(90, 'GT', 'Guatemala', 1, 0),
(91, 'XU', 'Guernsey and Alderney', 1, 0),
(92, 'GN', 'Guinea', 1, 0),
(93, 'GW', 'Guinea-Bissau', 1, 0),
(94, 'GY', 'Guyana', 1, 0),
(95, 'HT', 'Haiti', 1, 0),
(96, 'HM', 'Heard and McDonald Islands', 1, 0),
(97, 'HN', 'Honduras', 1, 0),
(98, 'HK', 'Hong Kong S.A.R.', 1, 0),
(99, 'HU', 'Hungary', 1, 0),
(100, 'IS', 'Iceland', 1, 0),
(101, 'IN', 'India', 1, 0),
(102, 'ID', 'Indonesia', 1, 0),
(103, 'IR', 'Iran', 1, 0),
(104, 'IQ', 'Iraq', 1, 0),
(105, 'IE', 'Ireland', 1, 0),
(106, 'IL', 'Israel', 1, 0),
(107, 'IT', 'Italy', 1, 0),
(108, 'JM', 'Jamaica', 1, 0),
(109, 'JP', 'Japan', 1, 0),
(110, 'XJ', 'Jersey', 1, 0),
(111, 'JO', 'Jordan', 1, 0),
(112, 'KZ', 'Kazakhstan', 1, 0),
(113, 'KE', 'Kenya', 1, 0),
(114, 'KI', 'Kiribati', 1, 0),
(115, 'KP', 'Korea North', 1, 0),
(116, 'KR', 'Korea South', 1, 0),
(117, 'KW', 'Kuwait', 1, 0),
(118, 'KG', 'Kyrgyzstan', 1, 0),
(119, 'LA', 'Laos', 1, 0),
(120, 'LV', 'Latvia', 1, 0),
(121, 'LB', 'Lebanon', 1, 0),
(122, 'LS', 'Lesotho', 1, 0),
(123, 'LR', 'Liberia', 1, 0),
(124, 'LY', 'Libya', 1, 0),
(125, 'LI', 'Liechtenstein', 1, 0),
(126, 'LT', 'Lithuania', 1, 0),
(127, 'LU', 'Luxembourg', 1, 0),
(128, 'MO', 'Macau S.A.R.', 1, 0),
(129, 'MK', 'Macedonia', 1, 0),
(130, 'MG', 'Madagascar', 1, 0),
(131, 'MW', 'Malawi', 1, 0),
(132, 'MY', 'Malaysia', 1, 0),
(133, 'MV', 'Maldives', 1, 0),
(134, 'ML', 'Mali', 1, 0),
(135, 'MT', 'Malta', 1, 0),
(136, 'XM', 'Man (Isle of)', 1, 0),
(137, 'MH', 'Marshall Islands', 1, 0),
(138, 'MQ', 'Martinique', 1, 0),
(139, 'MR', 'Mauritania', 1, 0),
(140, 'MU', 'Mauritius', 1, 0),
(141, 'YT', 'Mayotte', 1, 0),
(142, 'MX', 'Mexico', 1, 0),
(143, 'FM', 'Micronesia', 1, 0),
(144, 'MD', 'Moldova', 1, 0),
(145, 'MC', 'Monaco', 1, 0),
(146, 'MN', 'Mongolia', 1, 0),
(147, 'MS', 'Montserrat', 1, 0),
(148, 'MA', 'Morocco', 1, 0),
(149, 'MZ', 'Mozambique', 1, 0),
(150, 'MM', 'Myanmar', 1, 0),
(151, 'NA', 'Namibia', 1, 0),
(152, 'NR', 'Nauru', 1, 0),
(153, 'NP', 'Nepal', 1, 0),
(154, 'AN', 'Netherlands Antilles', 1, 0),
(155, 'NL', 'Netherlands The', 1, 0),
(156, 'NC', 'New Caledonia', 1, 0),
(157, 'NZ', 'New Zealand', 1, 0),
(158, 'NI', 'Nicaragua', 1, 0),
(159, 'NE', 'Niger', 1, 0),
(160, 'NG', 'Nigeria', 1, 1),
(161, 'NU', 'Niue', 1, 0),
(162, 'NF', 'Norfolk Island', 1, 0),
(163, 'MP', 'Northern Mariana Islands', 1, 0),
(164, 'NO', 'Norway', 1, 0),
(165, 'OM', 'Oman', 1, 0),
(166, 'PK', 'Pakistan', 1, 0),
(167, 'PW', 'Palau', 1, 0),
(168, 'PS', 'Palestinian Territory Occupied', 1, 0),
(169, 'PA', 'Panama', 1, 0),
(170, 'PG', 'Papua new Guinea', 1, 0),
(171, 'PY', 'Paraguay', 1, 0),
(172, 'PE', 'Peru', 1, 0),
(173, 'PH', 'Philippines', 1, 0),
(174, 'PN', 'Pitcairn Island', 1, 0),
(175, 'PL', 'Poland', 1, 0),
(176, 'PT', 'Portugal', 1, 0),
(177, 'PR', 'Puerto Rico', 1, 0),
(178, 'QA', 'Qatar', 1, 0),
(179, 'RE', 'Reunion', 1, 0),
(180, 'RO', 'Romania', 1, 0),
(181, 'RU', 'Russia', 1, 0),
(182, 'RW', 'Rwanda', 1, 0),
(183, 'SH', 'Saint Helena', 1, 0),
(184, 'KN', 'Saint Kitts And Nevis', 1, 0),
(185, 'LC', 'Saint Lucia', 1, 0),
(186, 'PM', 'Saint Pierre and Miquelon', 1, 0),
(187, 'VC', 'Saint Vincent And The Grenadines', 1, 0),
(188, 'WS', 'Samoa', 1, 0),
(189, 'SM', 'San Marino', 1, 0),
(190, 'ST', 'Sao Tome and Principe', 1, 0),
(191, 'SA', 'Saudi Arabia', 1, 0),
(192, 'SN', 'Senegal', 1, 0),
(193, 'RS', 'Serbia', 1, 0),
(194, 'SC', 'Seychelles', 1, 0),
(195, 'SL', 'Sierra Leone', 1, 0),
(196, 'SG', 'Singapore', 1, 0),
(197, 'SK', 'Slovakia', 1, 0),
(198, 'SI', 'Slovenia', 1, 0),
(199, 'XG', 'Smaller Territories of the UK', 1, 0),
(200, 'SB', 'Solomon Islands', 1, 0),
(201, 'SO', 'Somalia', 1, 0),
(202, 'ZA', 'South Africa', 1, 0),
(203, 'GS', 'South Georgia', 1, 0),
(204, 'SS', 'South Sudan', 1, 0),
(205, 'ES', 'Spain', 1, 0),
(206, 'LK', 'Sri Lanka', 1, 0),
(207, 'SD', 'Sudan', 1, 0),
(208, 'SR', 'Suriname', 1, 0),
(209, 'SJ', 'Svalbard And Jan Mayen Islands', 1, 0),
(210, 'SZ', 'Swaziland', 1, 0),
(211, 'SE', 'Sweden', 1, 0),
(212, 'CH', 'Switzerland', 1, 0),
(213, 'SY', 'Syria', 1, 0),
(214, 'TW', 'Taiwan', 1, 0),
(215, 'TJ', 'Tajikistan', 1, 0),
(216, 'TZ', 'Tanzania', 1, 0),
(217, 'TH', 'Thailand', 1, 0),
(218, 'TG', 'Togo', 1, 0),
(219, 'TK', 'Tokelau', 1, 0),
(220, 'TO', 'Tonga', 1, 0),
(221, 'TT', 'Trinidad And Tobago', 1, 0),
(222, 'TN', 'Tunisia', 1, 0),
(223, 'TR', 'Turkey', 1, 0),
(224, 'TM', 'Turkmenistan', 1, 0),
(225, 'TC', 'Turks And Caicos Islands', 1, 0),
(226, 'TV', 'Tuvalu', 1, 0),
(227, 'UG', 'Uganda', 1, 0),
(228, 'UA', 'Ukraine', 1, 0),
(229, 'AE', 'United Arab Emirates', 1, 0),
(230, 'GB', 'United Kingdom', 1, 0),
(231, 'US', 'United States', 1, 0),
(232, 'UM', 'United States Minor Outlying Islands', 1, 0),
(233, 'UY', 'Uruguay', 1, 0),
(234, 'UZ', 'Uzbekistan', 1, 0),
(235, 'VU', 'Vanuatu', 1, 0),
(236, 'VA', 'Vatican City State (Holy See)', 1, 0),
(237, 'VE', 'Venezuela', 1, 0),
(238, 'VN', 'Vietnam', 1, 0),
(239, 'VG', 'Virgin Islands (British)', 1, 0),
(240, 'VI', 'Virgin Islands (US)', 1, 0),
(241, 'WF', 'Wallis And Futuna Islands', 1, 0),
(242, 'EH', 'Western Sahara', 1, 0),
(243, 'YE', 'Yemen', 1, 0),
(244, 'YU', 'Yugoslavia', 1, 0),
(245, 'ZM', 'Zambia', 1, 0),
(246, 'ZW', 'Zimbabwe', 1, 0);